### ISSUE TITLE
The versions API is returning 404

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#15]
The [versions API](https://health.graphics/api/release/versions) is currently returning 404.

**Comment by csd713** [comment]
hello @armenzg I would like to take this up. Could you please give more details on expected solution?

**Comment by armenzg** [comment]
Hi @csd713 would you mind following the set README to set up the project?
You can then load https://health.graphics/api/release/versions and see what errors you see in the console.

**Comment by armenzg** [comment]
There's no recommended solution as I don't know why it is failing.
The related code is this: https://github.com/mozilla/firefox-health-backend/blob/master/src/release/versions.js

**Comment by csd713** [comment]
I have setup the project. I do not see any errors in console when I visit the version page. I will analyze further and get back.

**Comment by csd713** [comment]
Hi @armenzg here is my quick analysis.
I could not find the route for `/api/release/versions` in the code, so it is returning 404. Please let me know if I'm missing something.
Is there any document that I could use, to look up all the route's info and expected output?

**Comment by armenzg** [comment]
There's not much document. I inherited this app.

Now, I feel rather silly. The app use to be frontend and backend under the same domain, thus, when I loaded https://health.graphics/api/release/versions (old link in my browser history) I thought there was a problem.

The backend API can be visited in here:
https://firefox-health-backend.herokuapp.com/api/release/

Regardless, for learning purposes, try to understand these:
https://github.com/mozilla/firefox-health-backend/blob/master/src/app.js#L11
https://github.com/mozilla/firefox-health-backend/blob/master/src/app.js#L42
https://github.com/mozilla/firefox-health-backend/blob/master/src/release.js#L8-L47
