### ISSUE TITLE
When GOOGLE_API_KEY we should return a more meaningful error

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#16]
When doing local development I might forget to pass GOOGLE_API_KEY to the backend.
When I don't set the variable I get the following issue [1] when the quantum page is loaded on the frontend.

STR:
* On another tab start the frontend with `yarn start:local`
* Load this page: http://localhost:5000/quantum/

[1]
>   TypeError: Cannot destructure property `values` of 'undefined' or 'null'.
>       at Object.<anonymous> (/Users/armenzg/repos/health/backend/src/perf.js:27:22)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)
> 
> 
>   TypeError: Cannot destructure property `values` of 'undefined' or 'null'.
>       at Object.<anonymous> (/Users/armenzg/repos/health/backend/src/perf.js:27:22)
>       at <anonymous>
>       at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by gabru-md** [comment]
Hello,
I was trying to reproduce this error as it seemed to me an easy fix that maybe I could provide, but I could not reproduce the same error. [http://localhost:5000/quantum](http://localhost:5000/quantum) seems to redirect me back to [localhost:5000](http://localhost:5000). :sweat_smile:

**Comment by armenzg** [comment]
My apologies! I should have been clear that you have to set up the [frontend](https://github.com/mozilla/firefox-health-dashboard) at the same time as the backend.

You have to start the backend with `yarn start` (which starts the app on port 3000 and the frontend with `yarn start:local` (using `:local` will make the frontend talk to localhost:3000).

Once you load http://localhost:5000/quantum/64 (you now have to add '64') you will see on the output of the backend that there's an error.

Let me know if it does not work as explained.
Thanks @gabru-md !

**Comment by gabru-md** [comment]
Thank you for clarifying @armenzg . I did know that the frontend server was also needed. I've done exactly as you mentioned. :sweat_smile: 
Here is a screenshot of what I get as an output on the backend when I open up `quantum/64` page.
![health-firefox](https://user-images.githubusercontent.com/25414121/41368199-db419dc4-6f5e-11e8-8661-b7643a1eb82f.png)

**Comment by armenzg** [comment]
Hi @gabru-md I just wanted to let you know that I'm on a conference this week and it's been hard to make time to get back to you. I will get back to you as soon as I have a bit more time over the next few days.

**Comment by armenzg** [comment]
Hi @gabru-md I think this might have got fixed while I was away on vacation.
I can't reproduce the issue as you pointed out.
Thanks for trying!
