### ISSUE TITLE
Pre-cache Nimbledroid cache

### ISSUE THREAD

**Issue by armenzg** [mozilla/firefox-health-backend#40]
Heroku has a scheduler we can use to warm up the cache for the Nimbledroid API.

**Comment by armenzg** [comment]
It seems we're hitting intermittently the 30 seconds time out on Heroku.

Here's a description of what happens with our API:
* Here's the [link](https://firefox-health-backend.herokuapp.com/api/android/nimbledroid/?product=klar) to the backend API (?product=klar)
* If not cached, we fetch Nimbledroid [apks endpoint](https://nimbledroid.com/api/v2/users/npark@mozilla.com/apps/org.mozilla.klar/apks) for focus OR klar data.
* This is [the code](https://github.com/mozilla/firefox-health-backend/blob/master/src/utils/NimbledroidClient/index.js) that fetches the data
* This is a reduced [sample data](https://github.com/mozilla/firefox-health-backend/blob/master/test/mocks/nimbledroidKlar.json)
* If I load the API on my browser:
  * Over the wire only less than 200Kb is tranferred. 2.32Mb on disk
  * Reaching the API with my browser takes close to 19 seconds
     * Reloading a second time does **not** take any less time

This is my request header:
> Host: nimbledroid.com
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Cookie: jv_visits_count_RrF4dO2hnf=2; G_ENABLED_IDPS=google; _nimbleweb_session=ccef691c10c5a5f783b5330f0a4db5b1
> DNT: 1
> Authorization: Basic <REMOVED>
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> If-None-Match: W/"37474d70bd847932b0e1e1555c949270"
> Cache-Control: max-age=0

This is the response header:
> HTTP/1.1 200 OK
> Cache-Control: max-age=0, private, must-revalidate
> Content-Encoding: gzip
> Content-Type: application/json
> Date: Mon, 16 Jul 2018 12:58:45 GMT
> ETag: W/"a2d37c80011e8450a67e9f7063232078"
> Server: nginx/1.4.6 (Ubuntu)
> Status: 200 OK
> Strict-Transport-Security: max-age=0; includeSubdomains
> Vary: Accept-Encoding
> X-Request-Id: fbdf6d30-c643-41a8-81ed-6f9db34fecd8
> X-Runtime: 19.086367
> transfer-encoding: chunked
> Connection: keep-alive

**Comment by cpeterso** [comment]
How often does the Fx health backend poll the Nimbledroid API today? No-Jun said he thinks our backend polls Nimbledroid every 30 minutes.

We start a Nimbledroid test run after every commit to the focus-android GitHub repo. (Each test run takes 1-2 hours.) There are typically 0-10 commits per day, so polling Nimbledroid every 30 minutes is probably frequent enough.

**Comment by armenzg** [comment]
CC @edmorley 

I'm not using any frequency at the moment.

The frontend hits the backend; if there's cached data we return. If it's timed out, we fetch from Nimbledroid.

**Comment by armenzg** [comment]
Some of what we discussed yesterday is that I will look at using Heroku's scheduler to run a script that will fetch the data on a schedule. That script will then put the data in Redis and be ready for when the API needs it.

**Comment by armenzg** [comment]
This got fixed with PR #44
