### ISSUE TITLE
Set an appropriate User-Agent when making requests to Treeherder

### ISSUE THREAD

**Issue by edmorley** [mozilla/firefox-health-backend#53]
Hi!

Treeherder's API docs request that users set a custom user agent when making requests to our API:
https://treeherder.readthedocs.io/rest_api.html#user-agents

...so that it's easier for us to track down (a) cases of inadvertent DOS, (b) users who are using a deprecated API, etc.

Currently firefox-health-backend does not do this for the requests made here (I had to manually search using GitHub code and the request URL to find out the source):
https://github.com/mozilla/firefox-health-backend/blob/3a67fdef9120c894416b6a0c0e2412357ef2707f/src/perf.js#L61

Treeherder already blocks most http libraries default User Agents (`node-fetch/...` just happened to not be in the list yet), and will be expanding that list soon, so it is important to set one here to prevent requests from failing when we do so.

Many thanks!

**Comment by edmorley** [comment]
It looks like the header should be set here:
https://github.com/mozilla/firefox-health-backend/blob/3a67fdef9120c894416b6a0c0e2412357ef2707f/src/fetch/text.js#L17

**Comment by armenzg** [comment]
There's only two more widgets that use this backend to get Treeherder data.
The aim is to kill those widgets with the new frontend component that fetches Treeherder directly.

**Comment by armenzg** [comment]
See https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/251
