### ISSUE TITLE
change in fetch from nimbledroid

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/firefox-health-backend#71]
see https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/591

**Comment by klahnakoski** [comment]
@armenzg  Here is a test of the backend for the new product

https://firefox-health-backend.herokuapp.com/api/android/nimbledroid?product=org.mozilla.fenix.nightly

I *think* we need to work with @mcomella to add new API keys.

https://nimbledroid.com/dashboard/Mozilla/nimbledroid-admin@mozilla.com/org.mozilla.fenix.nightly/6b5dbddf-86f2-42e8-bf2d-58044c796b5c...c32ae9eb-dae6-4e69-bd34-072561e3b5a2?os_version=android5

**Comment by armenzg** [comment]
If you have a Nimbledroid account, you can create a new one in here https://nimbledroid.com/account

If you prefer, I can regenerate the key on my account and give it to you to test out.

**Comment by mcomella** [comment]
As far as I know, we need to use the API keys from the account that uploaded the build, i.e. nimbledroid-admin. I can send those to Kyle.

**Comment by mcomella** [comment]
Confusion cleared: I will work with armenzg. :)

**Comment by armenzg** [comment]
I have made some code improvements to handle a new state and empty data being returned.

@mcomella is it expected that three of the products do not return data? See log.

```
armenzg@Armens-MacBook-Pro firefox-health-backend % DEBUG=script:info,script:error yarn fetchNimbledroidData
yarn run v1.19.0
$ yarn build && node build/nimbledroid.js
$ webpack --mode production
Hash: 0dd611553c27e4a0908f
Version: webpack 4.39.2
Time: 1517ms
Built at: 11/26/2019 3:44:01 PM
             Asset      Size  Chunks             Chunk Names
          index.js  27.2 KiB       0  [emitted]  index
      index.js.map  84.1 KiB       0  [emitted]  index
    nimbledroid.js  4.16 KiB       1  [emitted]  nimbledroid
nimbledroid.js.map  14.8 KiB       1  [emitted]  nimbledroid
  script:info Fetching each product can take between 20-40 seconds. +0ms
  script:info Fetching org.mozilla.fenix +1ms
  script:info Fetching org.mozilla.fenix.nightly +12ms
  script:info Fetching org.mozilla.reference.browser +1ms
  script:info Fetching org.mozilla.geckoview_example +0ms
  script:info Fetching com.chrome.beta +1ms
  script:error There was nothing to be stored from https://nimbledroid.com/api/v2/users/nimbledroid-admin@mozilla.com/apps/com.chrome.beta/apks +0ms
  script:error There was nothing to be stored from https://nimbledroid.com/api/v2/users/nimbledroid-admin@mozilla.com/apps/org.mozilla.geckoview_example/apks +0ms
  script:error There was nothing to be stored from https://nimbledroid.com/api/v2/users/nimbledroid-admin@mozilla.com/apps/org.mozilla.fenix/apks +5ms
  script:info Storing org.mozilla.reference.browser +1s
  script:info Storing org.mozilla.fenix.nightly +2s
✨  Done in 6.47s
```

**Comment by mcomella** [comment]
> @mcomella is it expected that three of the products do not return data? See log.

Yes:
- we're working to fix Nightly uploads: https://github.com/mozilla-mobile/perf-frontend-issues/issues/21
- We may resume Chrome uploads in the future
- We don't upload geckoviewExample
